server:
  port: 8762

configuration:
  sd-host: localhost
  sd-port: 8761
  sd-path: /eureka
  sidecar:
    type: @sidecar-type@


spring:
  application:
    name: sidecar-@sidecar-type@

sidecar:
  hostname: localhost
  port: 5432
  health-uri: http://localhost:${server.port}/health/delegating-status

eureka:
  client:
    serviceUrl:
      defaultZone: http://${configuration.sd-host}:${configuration.sd-port}${configuration.sd-path}